"""Prompt construction and the deterministic response templates.

Two things live here:

1. The system prompt, assembled per turn from retrieved passages, the triage
   floor and any restricted intent that fired.
2. The emergency and crisis cards, which are **not** generated by a model.
   When a red flag fires, the words a user sees are fixed text from this file.
   A paraphrased ambulance number is a defect with a body count, so that path
   contains no sampling at all.
"""

from __future__ import annotations

from .config import MEDICAL_DISCLAIMER
from .language import LANGUAGE_NAMES
from .retrieval import RetrievalResult
from .safety import SafetyReport
from .triage import LEVELS, TriageResult, Urgency

SYSTEM_TEMPLATE = """You are {app_name}, a health information assistant for an Indian audience.

## What you are
A careful, plain-spoken guide that helps people understand a health concern and decide what to do next. You are not a doctor and you never pretend to be one.

## Language
Reply entirely in {language_name}. Match the user's register: simple, warm, concrete. Do not mix languages unless the user did.

## Grounding rules
- Answer using ONLY the numbered sources below. They are the curated knowledge base.
- **Cite inline, in every reply.** Put the source tag at the end of each sentence or
  bullet that states a fact, like this:
      - Give small sips frequently rather than large amounts at once. [S2]
      - A cough lasting more than two weeks should be checked for TB. [S1][S3]
  An answer with no [S] tag at all is a failed answer, even if the content is correct.
  Tags are the reader's only way to check you, and they are validated after you reply.
- If the sources do not cover the question, say plainly that this is outside what you can advise on, and point to the kind of clinician who can help. Never fill a gap with recalled medical knowledge.
- Never invent a phone number, a drug name, a dose, a statistic or a guideline.

## Hard limits, never break these
1. Do not diagnose. You may say what a pattern is "consistent with" and what would need ruling out, but the diagnosis belongs to a clinician who can examine and test.
2. Do not prescribe. No drug choice, no dose, no frequency, no duration, no "you can take X". Refer dose questions to a pharmacist or doctor.
3. Do not interpret an individual test report as normal or abnormal. Give the general reference range from the sources and say the ordering clinician must read it in context.
4. Do not promise an outcome, a cure or a timeline for recovery.
5. Do not discourage anyone from seeking care, and never suggest waiting when the assessment says otherwise.

## The assessment for this message
Urgency has already been assessed by a rule engine as **{urgency_label}** ({urgency_timeframe}).
{urgency_reasons}
Write your answer consistent with that level. If the user's message contains something the rules may have missed and you believe it is MORE urgent, say so clearly and raise the level. Never write anything that implies a lower urgency than the level above.

## Answer shape
- Open with one or two sentences that answer the actual question and acknowledge the concern. No preamble, no restating the question.
- Then the practical content, in short bullets. What to do, what to watch for.
- Then a clearly marked section of specific warning signs that mean "seek care now", drawn from the sources.
- Close with the single most useful next step.
- Keep it under 250 words. Use markdown. Never use a table.
- Re-read your draft before sending: does every factual bullet carry its [S] tag,
  and does every number, threshold and phone number appear verbatim in a source?
  If a detail is not in the sources, cut it rather than recalling it.
- End your reply with a tag on its own final line: [[URGENCY: LEVEL]] where LEVEL is one of INFO, SELF_CARE, ROUTINE, URGENT, EMERGENCY. This tag is stripped before display.
{restricted_block}
## Sources
{sources}
"""

RESTRICTED_TEMPLATE = """
## A restricted request was detected in this message
{items}
Handle it exactly as described. Decline the restricted part warmly and briefly, without lecturing, then give the user the most useful thing you can offer instead.
"""

NO_CONTEXT_NOTE = (
    "No source in the knowledge base matched this question closely. Say so directly, "
    "explain what the assistant does cover, and suggest who to ask instead. Do not "
    "answer from general knowledge."
)

CLARIFY_NOTE = """The user has described a symptom, but too vaguely to match anything specific in the knowledge base.

Do NOT refuse, and do NOT guess at a cause. Ask the questions a clinician would ask first:
- what exactly they feel, and where in the body
- how long it has been going on, and whether it is getting worse
- what else is happening alongside it
- who it is for, and roughly what age

Ask at most four, as short bullets. Under 120 words. Warm and direct, no preamble.
Finish with the exception that overrides all of it: if the symptom is severe and came on
suddenly, involves the chest, or comes with breathlessness, confusion, fainting or heavy
bleeding, they should call 112 now rather than answering questions.
Do not cite sources for a clarifying question; there is nothing to cite yet."""


def format_sources(retrieval: RetrievalResult) -> str:
    if not retrieval.hits:
        return "(none)"
    blocks = []
    for i, hit in enumerate(retrieval.hits, start=1):
        chunk = hit.chunk
        blocks.append(
            f"[S{i}] {chunk.doc_title} — {chunk.heading}\n"
            f"(source: {chunk.source}; reviewed {chunk.last_reviewed})\n"
            f"{chunk.text}"
        )
    return "\n\n".join(blocks)


def build_system_prompt(
    *,
    app_name: str,
    language: str,
    triage: TriageResult,
    safety: SafetyReport,
    retrieval: RetrievalResult,
    vague: bool = False,
) -> str:
    meta = LEVELS[triage.level]
    reasons = "\n".join(f"- {r}" for r in triage.reasons) or "- No specific rule fired."

    restricted_block = ""
    if safety.restrictions:
        items = "\n".join(f"- **{r.label}**: {r.policy}" for r in safety.restrictions)
        restricted_block = RESTRICTED_TEMPLATE.format(items=items)

    sources = format_sources(retrieval)
    if vague:
        sources = f"{CLARIFY_NOTE}\n\n{sources}"
    elif not retrieval.grounded:
        sources = f"{NO_CONTEXT_NOTE}\n\n{sources}"

    return SYSTEM_TEMPLATE.format(
        app_name=app_name,
        language_name=LANGUAGE_NAMES.get(language, "English"),
        urgency_label=meta.label,
        urgency_timeframe=meta.timeframe,
        urgency_reasons=reasons,
        restricted_block=restricted_block,
        sources=sources,
    )


def build_messages(history: list[dict], user_message: str, max_turns: int = 6) -> list[dict]:
    """Trim history to the last few turns and append the new message."""
    trimmed = [
        {"role": m["role"], "content": m["content"]}
        for m in (history or [])
        if m.get("role") in {"user", "assistant"} and m.get("content")
    ][-max_turns * 2 :]
    return [*trimmed, {"role": "user", "content": user_message}]


# --------------------------------------------------------------------------
# deterministic cards
# --------------------------------------------------------------------------

_EMERGENCY_HEAD = {
    "en": "### This needs emergency care now\n\n**Call 112 immediately** (or 108 for an ambulance).",
    "hi": "### यह आपातकालीन स्थिति है\n\n**तुरंत 112 पर कॉल करें** (एम्बुलेंस के लिए 108)।",
    "bn": "### এটি জরুরি অবস্থা\n\n**এখনই 112 নম্বরে ফোন করুন** (অ্যাম্বুলেন্সের জন্য 108)।",
}
_EMERGENCY_WHY = {"en": "**Why:**", "hi": "**कारण:**", "bn": "**কারণ:**"}
_EMERGENCY_WAIT = {
    "en": "**While you wait for help:**",
    "hi": "**मदद आने तक:**",
    "bn": "**সাহায্য আসা পর্যন্ত:**",
}
_EMERGENCY_TAIL = {
    "en": "Do not drive yourself. Do not wait to see if it passes. If you are unsure, call anyway — that is what the number is for.",
    "hi": "खुद गाड़ी न चलाएँ। यह सोचकर इंतज़ार न करें कि अपने आप ठीक हो जाएगा। संदेह हो तो भी कॉल करें।",
    "bn": "নিজে গাড়ি চালাবেন না। নিজে থেকে ঠিক হয়ে যাবে ভেবে অপেক্ষা করবেন না। সন্দেহ হলেও ফোন করুন।",
}

_CRISIS = {
    "en": (
        "### You do not have to get through this alone\n\n"
        "What you are feeling right now is real, and it can change with the right support. "
        "Please talk to someone tonight.\n\n"
        "- **Tele-MANAS: 14416** — free, confidential, 24x7, in many Indian languages\n"
        "- **KIRAN: 1800-599-0019** — free, 24x7, 13 languages\n"
        "- **Vandrevala Foundation: 9999 666 555** — 24x7\n"
        "- **Emergency: 112** — if you are in immediate danger, or have already harmed yourself\n\n"
        "If you can, tell one person you trust and stay with them. Move anything you could "
        "use to hurt yourself out of your reach, or ask someone else to hold on to it.\n\n"
        "I am not able to give counselling myself, but the people on those lines are trained "
        "for exactly this conversation, and they will not judge you for making the call."
    ),
    "hi": (
        "### आपको यह अकेले नहीं झेलना है\n\n"
        "आप अभी जो महसूस कर रहे हैं वह सच्चा है, और सही मदद से यह बदल सकता है। "
        "कृपया आज ही किसी से बात करें।\n\n"
        "- **टेली-मानस: 14416** — निःशुल्क, गोपनीय, 24x7\n"
        "- **किरण: 1800-599-0019** — निःशुल्क, 24x7\n"
        "- **वंद्रेवाला फाउंडेशन: 9999 666 555** — 24x7\n"
        "- **आपातकाल: 112** — यदि तत्काल खतरा है\n\n"
        "हो सके तो किसी भरोसेमंद व्यक्ति को बताएं और उनके साथ रहें। जिन चीज़ों से आप "
        "खुद को नुकसान पहुँचा सकते हैं, उन्हें अपने से दूर कर दें।\n\n"
        "मैं खुद परामर्श नहीं दे सकता, लेकिन इन हेल्पलाइन पर बैठे लोग इसी बातचीत के लिए "
        "प्रशिक्षित हैं।"
    ),
    "bn": (
        "### আপনাকে একা এর মধ্য দিয়ে যেতে হবে না\n\n"
        "আপনি এখন যা অনুভব করছেন তা সত্যি, এবং সঠিক সহায়তায় তা বদলাতে পারে। "
        "আজই কারও সঙ্গে কথা বলুন।\n\n"
        "- **টেলি-মানস: 14416** — বিনামূল্যে, গোপনীয়, 24x7\n"
        "- **কিরণ: 1800-599-0019** — বিনামূল্যে, 24x7\n"
        "- **বন্দ্রেওয়ালা ফাউন্ডেশন: 9999 666 555** — 24x7\n"
        "- **জরুরি: 112** — তাৎক্ষণিক বিপদ হলে\n\n"
        "সম্ভব হলে বিশ্বস্ত একজনকে জানান এবং তাঁর সঙ্গে থাকুন। যা দিয়ে নিজের ক্ষতি করতে "
        "পারেন, তা নিজের কাছ থেকে সরিয়ে রাখুন।\n\n"
        "আমি নিজে কাউন্সেলিং দিতে পারি না, কিন্তু এই হেল্পলাইনের মানুষজন ঠিক এই "
        "কথোপকথনের জন্যই প্রশিক্ষিত।"
    ),
}


def emergency_card(safety: SafetyReport, language: str = "en") -> str:
    """Fixed-text emergency response. No model involved."""
    lang = language if language in _EMERGENCY_HEAD else "en"
    flags = [f for f in safety.red_flags if f.urgency == "EMERGENCY"] or safety.red_flags

    why = "\n".join(f"- {f.label_in(lang)}" for f in flags)
    steps = "\n".join(f"- {f.guidance_in(lang)}" for f in flags if f.guidance_in(lang))

    parts = [_EMERGENCY_HEAD[lang], f"{_EMERGENCY_WHY[lang]}\n{why}"]
    if steps:
        parts.append(f"{_EMERGENCY_WAIT[lang]}\n{steps}")
    parts.append(_EMERGENCY_TAIL[lang])
    return "\n\n".join(parts)


def crisis_card(language: str = "en") -> str:
    """Fixed-text response for self-harm risk. No model involved."""
    return _CRISIS.get(language, _CRISIS["en"])


_RESTRICTED_NOTES = {
    "prescription_request": {
        "en": (
            "I can't recommend a medicine or a dose. That depends on weight, kidney and "
            "liver function, pregnancy status and everything else you take, so it has to "
            "come from a doctor or pharmacist who can ask those questions. Here is the "
            "general safety information I do have:"
        ),
        "hi": (
            "मैं कोई दवा या उसकी खुराक नहीं बता सकता। यह वज़न, किडनी और लिवर की स्थिति, "
            "गर्भावस्था और आपकी बाकी दवाओं पर निर्भर करता है, इसलिए यह डॉक्टर या फार्मासिस्ट "
            "ही तय कर सकते हैं। सामान्य सुरक्षा जानकारी यह है:"
        ),
        "bn": (
            "আমি কোনও ওষুধ বা তার ডোজ বলতে পারি না। এটি ওজন, কিডনি ও লিভারের অবস্থা, "
            "গর্ভাবস্থা এবং আপনার অন্যান্য ওষুধের উপর নির্ভর করে, তাই ডাক্তার বা ফার্মাসিস্টই "
            "এটি ঠিক করবেন। সাধারণ নিরাপত্তা তথ্য এখানে দেওয়া হল:"
        ),
    },
    "diagnosis_request": {
        "en": (
            "I can't tell you which condition you have — that needs an examination and "
            "tests. What I can do is show you what the guidance says about these symptoms "
            "and when to get them checked:"
        ),
        "hi": (
            "आपको कौन सी बीमारी है, यह मैं नहीं बता सकता — इसके लिए जाँच ज़रूरी है। "
            "मैं इतना बता सकता हूँ कि इन लक्षणों के बारे में दिशानिर्देश क्या कहते हैं:"
        ),
        "bn": (
            "আপনার কী রোগ হয়েছে তা আমি বলতে পারি না — এর জন্য পরীক্ষা প্রয়োজন। "
            "এই উপসর্গ সম্পর্কে নির্দেশিকা কী বলে, তা আমি জানাতে পারি:"
        ),
    },
    "test_interpretation": {
        "en": (
            "I can't interpret an individual report. The clinician who ordered it has to "
            "read it alongside your history and examination. These are the general "
            "reference ranges:"
        ),
        "hi": (
            "मैं किसी रिपोर्ट को नहीं पढ़ सकता — जिस डॉक्टर ने जाँच लिखी है, वही इसे आपके "
            "इतिहास के साथ देखेंगे। सामान्य संदर्भ सीमाएँ ये हैं:"
        ),
        "bn": (
            "আমি কোনও রিপোর্ট ব্যাখ্যা করতে পারি না — যিনি পরীক্ষা দিয়েছেন তিনিই আপনার "
            "ইতিহাসের সঙ্গে মিলিয়ে দেখবেন। সাধারণ রেফারেন্স রেঞ্জ এইগুলি:"
        ),
    },
}


def restricted_note(restriction_id: str, language: str = "en") -> str:
    """Short user-facing decline used on the extractive path.

    The model path gets the full policy in its system prompt. Without a model
    the refusal still has to be said out loud, otherwise "which antibiotic
    should I take" is answered with a wall of antibiotic guidance and no
    acknowledgement that the question was declined.
    """
    variants = _RESTRICTED_NOTES.get(restriction_id, {})
    return variants.get(language) or variants.get("en", "")


_CLARIFY = {
    "en": (
        "I can help with this — I just need a bit more to point you the right way.\n\n"
        "- **What does it feel like, and where?** For example aching, burning, cramping, "
        "sharp; in the head, chest, stomach, back, a joint.\n"
        "- **How long has it been there**, and is it getting worse?\n"
        "- **Anything alongside it** — fever, vomiting, breathlessness, a rash, an injury?\n"
        "- **Who is this for**, and roughly what age?\n\n"
        "One exception, and it matters more than any of the above: if the pain is severe "
        "and came on suddenly, is in the chest, or comes with breathlessness, confusion, "
        "fainting or heavy bleeding — **call 112 now** instead of answering these."
    ),
    "hi": (
        "मैं मदद कर सकता हूँ — बस थोड़ी और जानकारी चाहिए।\n\n"
        "- **कैसा महसूस हो रहा है और कहाँ?** जैसे जलन, ऐंठन, तेज़ चुभन; सिर, छाती, पेट, "
        "कमर या किसी जोड़ में।\n"
        "- **कब से है**, और क्या बढ़ रहा है?\n"
        "- **साथ में और क्या है** — बुखार, उल्टी, साँस फूलना, दाने, कोई चोट?\n"
        "- **किसके लिए पूछ रहे हैं**, और उम्र लगभग कितनी है?\n\n"
        "एक बात इन सबसे ज़्यादा ज़रूरी है: अगर दर्द अचानक और बहुत तेज़ है, छाती में है, या "
        "साथ में साँस फूलना, भ्रम, बेहोशी या ज़्यादा खून बह रहा है — **तुरंत 112 पर कॉल करें**।"
    ),
    "bn": (
        "আমি সাহায্য করতে পারি — শুধু আর একটু জানা দরকার।\n\n"
        "- **কেমন লাগছে এবং কোথায়?** যেমন জ্বালা, খিঁচ ধরা, তীক্ষ্ণ ব্যথা; মাথা, বুক, পেট, "
        "কোমর বা কোনও গাঁটে।\n"
        "- **কতদিন ধরে**, এবং বাড়ছে কি?\n"
        "- **সঙ্গে আর কী আছে** — জ্বর, বমি, শ্বাসকষ্ট, র‍্যাশ, কোনও আঘাত?\n"
        "- **কার জন্য জানতে চাইছেন**, বয়স আনুমানিক কত?\n\n"
        "একটি কথা এ সবের চেয়ে জরুরি: ব্যথা যদি হঠাৎ ও তীব্র হয়, বুকে হয়, বা সঙ্গে শ্বাসকষ্ট, "
        "বিভ্রান্তি, অজ্ঞান হওয়া বা প্রচুর রক্তপাত থাকে — **এখনই 112 নম্বরে ফোন করুন**।"
    ),
}


def clarify_card(language: str = "en") -> str:
    """Asked when a message is clearly about health but too vague to ground.

    Used on the extractive path, which is what runs when no model key is set.
    Telling someone who just said "I am in pain" that their question is not in
    the knowledge base is the single worst answer this system could give, and
    for a while it was the answer it gave.
    """
    return _CLARIFY.get(language, _CLARIFY["en"])


def disclaimer_for(language: str = "en") -> str:
    return {
        "en": MEDICAL_DISCLAIMER,
        "hi": (
            "CareCompass सामान्य स्वास्थ्य जानकारी देता है। यह निदान या दवा नहीं देता "
            "और डॉक्टर का विकल्प नहीं है। आपात स्थिति में 112 पर कॉल करें।"
        ),
        "bn": (
            "CareCompass সাধারণ স্বাস্থ্য তথ্য দেয়। এটি রোগ নির্ণয় বা ওষুধ দেয় না এবং "
            "ডাক্তারের বিকল্প নয়। জরুরি অবস্থায় 112 নম্বরে ফোন করুন।"
        ),
    }.get(language, MEDICAL_DISCLAIMER)
